title: Darsh Gupta | Aerospace, RF & Embedded Systems
description: Portfolio of aerospace, RF, and embedded systems projects
author: Darsh Gupta
email: darshgu77@gmail.com
url: https://iamdarshg.github.io
baseurl: ""
permalink: pretty

exclude:
  - .git
  - .gitignore
  - README.md
  - LICENSE

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
